/** Teaching defaults for newly generated content; saved game contracts stay unchanged. */
export const SIMPLE_LESSON_STYLE = `BEGINNER-FIRST LESSON STYLE (applies at every learner level):
Teach the simplest useful source-backed idea within the requested focus. Start with an everyday explanation of what it does and why it matters, then a concrete example, then a small action. Assume no familiarity with this topic. A technical source or a college audience is not a request for a technical puzzle. For a broad focus, prefer a foundational relationship over an optimization, derivation or special case. If the source only supports a specialized concept, explain that concept's basic purpose using only supported claims; do not invent missing foundations or silently change the topic.
Introduce at most two essential new technical terms per activity, each defined in ordinary words BEFORE asking the player to use it. Put familiar language first and the technical name in parentheses when useful. Use short everyday labels rather than acronyms, symbols or strings of parameters. Every prose field must be a complete thought ending in sentence punctuation. Aim well below its character limit; rewrite more briefly rather than cutting a sentence or packing in extra clauses. Never leave a dangling instruction. Respect the learner's age without baby talk.
Use one thing to change or one distinction to sort at a time. The first case explains the relationship and shows one small worked example before asking for a different application. The second changes just one meaningful observation or way of presenting the example, reminds the player of the same principle, and remains equally short. Merely swapping a noun or shuffling the same cards is not a new application. Use fresh neutral card labels and a different answer pattern so players must inspect the evidence; explain any new presentation convention before sorting. A transfer case means gentle practice, not a difficulty spike or a new concept.
Keep the adventure briefing to its purpose and first step; keep the machine briefing to its one teaching principle. Do not repeat the full route or tutorial in every field. Make the current action, visible goal and reason clear in two or three short sentences, ideally 25–45 words total. Feedback should be one or two short sentences: what happened, why, and one useful next action after a miss. No multi-step mental arithmetic, formula memorization, unexplained percentages, dense notation, compound targets or secret settings. Prefer visible comparisons and small whole numbers. When mathematics is the actual topic, let the apparatus perform the calculation and teach the intuition needed to interpret it.
Keep learning meaningful: the player must apply a source-backed relationship or distinction, not copy a complete answer or match identical words. Shorten the required task rather than removing the explanation that makes it solvable. Keep essential assumptions and units wherever needed for correctness; put extended detail and caveats in model notes/discoveries. Simplification must never turn a limited claim into a universal claim.`;

export const SIMPLE_LESSON_REVIEW = `BEGINNER ACCESSIBILITY CHECK: Trace the learner's first action using only text they have seen BEFORE acting. Block any unfinished or truncated sentence in required teaching or story copy, even if another field repeats the missing instruction. Block an unexplained essential term, a prerequisite the lesson never teaches, multi-step arithmetic needed to solve the task, a goal requiring several simultaneous decisions, or a transfer case introducing another concept. Request a concrete simpler rewrite within the same objective. A short prompt alone is not evidence of accessibility. Check that the first case teaches a usable principle with a small example and that feedback explains a miss without dumping the answer. Preserve source truth when simplifying. Minor wording preferences are advisory; actual missing instruction is blocking.`;
